{"args": [], "created": 1743077157.79596, "dagster_meta": {"name": "sensor_tiempo_pasos", "orig_message": "Error al procesar tiempos de ejecuci\u00f3n: 'DagsterInstance' object has no attribute 'get_logs_for_run'", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_tiempo_pasos", "levelname": "ERROR", "levelno": 40, "lineno": 512, "module": "definitions", "msecs": 795.0, "msg": "__repository__ - sensor_tiempo_pasos - Error al procesar tiempos de ejecuci\u00f3n: 'DagsterInstance' object has no attribute 'get_logs_for_run'", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 21208, "processName": "MainProcess", "relativeCreated": 35165.67802429199, "stack_info": null, "taskName": null, "thread": 22824, "threadName": "ThreadPoolExecutor-0_0"}
{"args": [], "created": 1743077157.8004727, "dagster_meta": {"name": "sensor_tiempo_pasos", "orig_message": "Traceback (most recent call last):\n  File \"C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py\", line 443, in sensor_tiempo_pasos\n    logs = context.instance.get_logs_for_run(run.run_id)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'DagsterInstance' object has no attribute 'get_logs_for_run'. Did you mean: 'get_records_for_run'?\n", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_tiempo_pasos", "levelname": "ERROR", "levelno": 40, "lineno": 514, "module": "definitions", "msecs": 800.0, "msg": "__repository__ - sensor_tiempo_pasos - Traceback (most recent call last):\n  File \"C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py\", line 443, in sensor_tiempo_pasos\n    logs = context.instance.get_logs_for_run(run.run_id)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'DagsterInstance' object has no attribute 'get_logs_for_run'. Did you mean: 'get_records_for_run'?\n", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 21208, "processName": "MainProcess", "relativeCreated": 35170.19081115723, "stack_info": null, "taskName": null, "thread": 22824, "threadName": "ThreadPoolExecutor-0_0"}
