{"args": [], "created": 1743076972.4724445, "dagster_meta": {"name": "sensor_de_exito_con_timestamps", "orig_message": "Error al procesar logs: 'DagsterInstance' object has no attribute 'get_logs_for_run'", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_de_exito_con_timestamps", "levelname": "ERROR", "levelno": 40, "lineno": 421, "module": "definitions", "msecs": 472.0, "msg": "__repository__ - sensor_de_exito_con_timestamps - Error al procesar logs: 'DagsterInstance' object has no attribute 'get_logs_for_run'", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 15288, "processName": "MainProcess", "relativeCreated": 63427.71768569946, "stack_info": null, "taskName": null, "thread": 32288, "threadName": "ThreadPoolExecutor-0_0"}
{"args": [], "created": 1743076972.4779541, "dagster_meta": {"name": "sensor_de_exito_con_timestamps", "orig_message": "Traceback (most recent call last):\n  File \"C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py\", line 346, in sensor_de_exito_con_timestamps\n    logs = context.instance.get_logs_for_run(run.run_id)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'DagsterInstance' object has no attribute 'get_logs_for_run'. Did you mean: 'get_records_for_run'?\n", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_de_exito_con_timestamps", "levelname": "ERROR", "levelno": 40, "lineno": 423, "module": "definitions", "msecs": 477.0, "msg": "__repository__ - sensor_de_exito_con_timestamps - Traceback (most recent call last):\n  File \"C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py\", line 346, in sensor_de_exito_con_timestamps\n    logs = context.instance.get_logs_for_run(run.run_id)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'DagsterInstance' object has no attribute 'get_logs_for_run'. Did you mean: 'get_records_for_run'?\n", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 15288, "processName": "MainProcess", "relativeCreated": 63433.22730064392, "stack_info": null, "taskName": null, "thread": 32288, "threadName": "ThreadPoolExecutor-0_0"}
{"args": [], "asctime": "2025-03-27 09:02:52 -0300", "created": 1743076972.47896, "dagster_meta": {"name": "sensor_de_exito_con_timestamps", "orig_message": "================================================================================", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_de_exito_con_timestamps", "levelname": "INFO", "levelno": 20, "lineno": 425, "message": "__repository__ - sensor_de_exito_con_timestamps - ================================================================================", "module": "definitions", "msecs": 478.0, "msg": "__repository__ - sensor_de_exito_con_timestamps - ================================================================================", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 15288, "processName": "MainProcess", "relativeCreated": 63434.23318862915, "stack_info": null, "taskName": null, "thread": 32288, "threadName": "ThreadPoolExecutor-0_0"}
